### get all tasks
GET http://localhost:3000/

### create task
POST http://localhost:3000/create
Content-Type: application/json

{
    "title": "Tarea-TASKCONTROLLER5",
    "completed": false
}

### get task by id
GET http://localhost:3000/id/65cd1f12ce02d078d43d79ab

### mark task completed
PUT http://localhost:3000/markAsCompleted/65cd1efece02d078d43d79a7

### change title
PUT http://localhost:3000/id/6201064b0028de7866e2b2c4
Content-Type: application/json

{
    "title": "Sacar la basura"
}

### deteled task
DELETE http://localhost:3000/id/65ce7e4868337fa8c7eb71c4